import Head from "next/head";
import styles from "@/styles/PageLayout.module.scss"
import Header from "@/components/Header";

export default function PageLayout( { children } ) {
  
  return (
    < >
      <Head>
        <title>Dev dog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.container}>
        <div>
          <main className={styles.main}>
            { children }
          </main>
        </div>
      </div>
      <footer className={styles.footer}>
        Created by leflores
      </footer>
    </>
  )
}
