import Head from 'next/head';
import { renderToString } from 'react-dom/server';

import BlogSidebar from '@/components/Blog/BlogSidebar';
import MDXProvider from '@/components/MDX/ComponentsProvider';
import Header from '@/components/Blog/PostHeader';
import Footer from '@/components/Footer';
import styles from '@/styles/Blog/BlogLayout.module.scss';

export default function BlogLayout({ children, meta }) {
  return (
    < >
      <Head>
        <title>Dev dog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="blog-wrapper">
        <BlogSidebar meta={meta} postTextContent={renderToString(children)} />
        <div className="blog-container">
          <Header />
          <div>
            <h1>{meta.title}</h1>
            <section className={styles.blogInfo}>
              <time className={styles.date}>{meta.date}</time>
              <p>{meta.description}</p>
              <div className={styles.tags}>
                <ul>
                  {
                    meta.tags.map((tag, index) => (
                      <li key={index}>
                        <span className={styles.tag} key={tag}>{tag}</span>
                      </li>
                    ))
                  }
                </ul>
              </div>
            </section>
            <MDXProvider>
              <main className={styles.main}>
                { children }
              </main>
            </MDXProvider>
            <Footer />
          </div>
        </div>
      </div>
    </>
  );
}
