import Head from "next/head";
import { renderToString } from "react-dom/server";

import styles from "@/styles/BlogLayout.module.scss"
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BlogSidebar from "@/components/blog/BlogSidebar";
import MDXProvider from "@/components/MDX/ComponentsProvider";

export default function BlogLayout( { children, meta } ) {

  return (
    < >
      <Head>
        <title>Dev dog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <BlogSidebar meta={meta} postTextContent={renderToString(children)} />
        <div>
          <Header />
          <div className="blog-container">
            <h1>{meta.title}</h1>
            <section className={styles.blogInfo}>
              <time className={styles.date}>{meta.date}</time>
              <p>{meta.description}</p>
              <div className={styles.tags}>
                <ul>
                  {
                    meta.tags.map(tag => (
                      <li>
                        <span className={styles.tag} key={tag}>{tag}</span>
                      </li>
                    ))
                  }
                </ul>
              </div>
            </section>
            <MDXProvider>
              <main className={styles.main}>
                { children }
              </main>
            </MDXProvider>
            <Footer />
          </div>
        </div>
      </div>
    </>
  )
}
