import Head from 'next/head';
import styles from '@/styles/HomeLayout.module.scss';
import Header from '@/components/Header';

export default function HomeLayout({ children }) {
  return (
    < >
      <Head>
        <title>Dev dog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.mainContainer}>
        { children }
      </main>
      <footer className={styles.footer}>
        Created by leflores
      </footer>
    </>
  );
}
